### ISSUE TITLE
Any specific reason to require `elixir ~> 1.12`?

### ISSUE THREAD

**Issue by sobolevn** [shirokovnv/phx_json_rpc#8]
I think it is safe to include older versions as well.
At least two of them.

Link: https://github.com/shirokovnv/phx_json_rpc/blob/master/mix.exs#L36
Refs #2

**Comment by shirokovnv** [comment]
Well, the package externally depends only on [ex_json_schema](https://github.com/jonasschmidt/ex_json_schema), which specs elixir minimal version as 1.6. But I didnt see any reasons to support  backaward compatibility so deeply. 

That's why I have chosen not the latest 1.12, as we have 1.13 as stable release and upcoming 1.14.

Anyway, support from 1.9 or 1.10 would be better, agreed.

**Comment by shirokovnv** [comment]
Minimum version setted to 1.10 in https://github.com/shirokovnv/phx_json_rpc/pull/17

**Comment by shirokovnv** [comment]
Can I close related issues?

**Comment by sobolevn** [comment]
Yes :)
